remove-empty = true
append-when-occupied = true
watch-config = true
renamers = ["classified", "constant"]

[names]
constant = "âœï¸ SCR"

[[names.classified]]
"ğŸ’¬ CHT" = ["discord", "dgg-chat", "Signal", "Mumble"]

[[names.classified]]
"ğŸŒ WEB" = ["librewolf"]

[[names.classified]]
"ğŸ—’ï¸  NTE" = ["Zathura", "obsidian"]

[[names.classified]]
"ğŸ² GME" = ["Steam", "Lutris"]

[[names.classified]]
"ğŸ’€ LOL" = ["leagueclientux.exe"]

[[names.classified]]
"â›ï¸  MC" = ["gdlauncher"]

[[names.classified]]
"ğŸ“¸ VID" = ["zoom"]

[[names.classified]]
"ğŸ§ MUS" = ["Spotify"]

[[names.classified]]
"ğŸ‘€ VID" = ["mpv"]
